baseURL = "https://mlaynedere.github.io/"
languageCode = "en-us"
title = "Mlaynedere Hacks"
theme = "monokai-vault"
## Pagination (paginate deprecated >=0.128)
[pagination]
  pagerSize = 10
defaultContentLanguage = "en"

[params]
  description = "Walkthroughs, CTF writeups, HackTheBox machines, notes."
  author = "Mlaynedere"
  showReadingTime = true
  enableSearch = true
  vaultSections = ["blog/hack-the-box"]
  codeCopy = true
  showTitleInHeader = false

[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.highlight]
  noClasses = false
  style = "monokai"
  lineNos = false
  lineNumbersInTable = false
  [markup.goldmark.renderer]
    unsafe = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  page = ["HTML"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

[permalinks]
  blog = "/blog/:slug/"

[menus]
  [[menus.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menus.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
